services:
  chrome:
    image: browserless/chrome:latest
    restart: unless-stopped
    ports:
      - '9222:3000'
    environment:
      - DEBUG=browserless:*
      - CONNECTION_TIMEOUT=60000
      - MAX_CONCURRENT_SESSIONS=10
      - ENABLE_DEBUGGER=true
