// @ts-check
const js = require('@eslint/js');
const globals = require('globals');
const boundariesPlugin = require('eslint-plugin-boundaries');
const growchatLoggingPlugin = require('./eslint-rules/index.cjs');

const srcTypes = [
  's-router',
  's-service',
  's-shared',
  's-utils',
  's-feature',
  's-admin',
  's-llm',
  's-chat',
  's-mcp',
  's-middleware',
  's-repository',
  's-bootstrap',
  's-config',
  's-durable',
  's-errors',
  's-validation',
  's-root',
];

module.exports = [
  js.configs.recommended,

  // Boundary rules — phased strict rollout: frontend-first warn baseline.
  // Frontend dependency rules are enforced; backend elements are registered
  // with permissive allow-all rules until stricter layering is rolled out.
  {
    plugins: {
      boundaries: boundariesPlugin,
      'growchat-logging': growchatLoggingPlugin,
    },
    settings: {
      'boundaries/root-path': process.cwd(),
      'boundaries/dependency-nodes': ['import', 'require', 'export'],
      'boundaries/elements': [
        // Frontend (public/js/)
        { type: 'f-bootstrap', pattern: 'public/js/bootstrap/**' },
        { type: 'f-feature', pattern: 'public/js/features/**' },
        { type: 'f-shared', pattern: 'public/js/shared/**' },
        { type: 'f-utils', pattern: 'public/js/utils/**' },
        // Backend (src/)
        { type: 's-router', pattern: 'src/routers/**' },
        { type: 's-service', pattern: 'src/services/**' },
        { type: 's-shared', pattern: 'src/shared/**' },
        { type: 's-utils', pattern: 'src/utils/**' },
        { type: 's-feature', pattern: 'src/features/**' },
        { type: 's-admin', pattern: 'src/admin/**' },
        { type: 's-llm', pattern: 'src/llm/**' },
        { type: 's-chat', pattern: 'src/chat/**' },
        { type: 's-mcp', pattern: 'src/mcp/**' },
        { type: 's-middleware', pattern: 'src/middleware/**' },
        { type: 's-repository', pattern: 'src/repositories/**' },
        { type: 's-bootstrap', pattern: 'src/bootstrap/**' },
        { type: 's-config', pattern: 'src/config/**' },
        { type: 's-durable', pattern: 'src/durable/**' },
        { type: 's-errors', pattern: 'src/errors/**' },
        { type: 's-validation', pattern: 'src/validation/**' },
        { type: 's-root', pattern: 'src/*', mode: 'file' },
        { type: 'test', pattern: 'tests/**' },
        { type: 'scripts', pattern: 'scripts/**' },
      ],
    },
    rules: {
      'boundaries/no-unknown': 'off',
      'boundaries/no-unknown-files': 'off',
      'boundaries/dependencies': [
        'warn',
        {
          default: 'disallow',
          rules: [
            // Frontend guardrails (preserved from original config)
            {
              from: { type: 'f-bootstrap' },
              allow: { to: { type: ['f-bootstrap', 'f-shared'] } },
            },
            {
              from: { type: 'f-feature' },
              allow: { to: { type: ['f-feature', 'f-shared'] } },
            },
            {
              from: { type: 'f-shared' },
              allow: { to: { type: ['f-shared'] } },
            },
            {
              from: { type: 'f-utils' },
              allow: { to: { type: ['f-utils', 'f-shared'] } },
            },
            {
              from: { type: 'scripts' },
              allow: { to: { type: ['scripts'] } },
            },
            {
              from: { type: 'test' },
              allow: {
                to: {
                  type: ['f-bootstrap', 'f-feature', 'f-shared', 'f-utils', 'test', 'scripts'],
                },
              },
            },
            // Backend permissive baseline — allow all src element types to import
            // from each other and from f-shared. TODO: tighten incrementally.
            {
              from: { type: srcTypes },
              allow: { to: { type: [...srcTypes, 'f-shared'] } },
            },
            // Tests may import from any src or frontend element type
            {
              from: { type: 'test' },
              allow: { to: { type: [...srcTypes, 'f-feature', 'f-shared'] } },
            },
            // src root-level files may import from test helpers
            {
              from: { type: 's-root' },
              allow: { to: { type: ['test'] } },
            },
            // src feature test files may import from frontend feature code
            {
              from: { type: 's-feature' },
              allow: { to: { type: ['f-feature'] } },
            },
            // src router test files may import from test helpers
            {
              from: { type: 's-router' },
              allow: { to: { type: ['test'] } },
            },
          ],
        },
      ],
    },
  },

  // Original project rules — strict defaults for new code
  {
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      'no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      'no-console': 'off',
      'growchat-logging/no-console-logging': 'error',
      'no-duplicate-imports': 'warn',
      complexity: ['warn', { max: 15 }],
      'max-lines-per-function': ['warn', { max: 120, skipBlankLines: true, skipComments: true }],
      'max-depth': ['warn', 4],
      'max-nested-callbacks': ['warn', 3],
    },
  },

  // Test files — relaxed limits for nesting, depth, and function length
  {
    files: ['tests/**/*.js', 'src/**/*.test.js'],
    rules: {
      'max-lines-per-function': 'off',
      'max-nested-callbacks': 'off',
      'max-depth': 'off',
      complexity: 'off',
      'no-unused-vars': 'off',
    },
  },

  // Large router and controller files — relaxed limits for legacy mega-functions.
  // TODO: Refactor these into sub-handlers and remove this override.
  {
    files: [
      'src/routers/admin.js',
      'src/routers/users.js',
      'src/routers/models.js',
      'src/routers/chat-message.js',
      'src/routers/chat-collection.js',
      'src/routers/auth.js',
      'src/routers/files.js',
      'src/routers/rbac.js',
      'src/routers/groups.js',
      'src/llm/stream-parser.js',
      'src/admin/tool-servers.js',
      'src/index.js',
      'public/js/features/chat/chat.js',
      'public/js/features/chat/chat-realtime-controller.js',
      'public/js/features/chat/chat-message-stream-send.js',
      'public/js/features/chat/message-input-controller.js',
      'public/js/features/chat/chat-message-stream-resume.js',
      'public/js/features/admin/settings/connections.js',
'public/js/features/admin/settings/connections-event-handlers.js',
'public/js/features/admin/settings/connections-modal-ops.js',
'public/js/features/admin/settings/connections-modal-form.js',
'public/js/features/admin/settings/connections-access-modal.js',
'public/js/features/admin/settings/connections-event-handlers.js',
'public/js/features/admin/settings/connections-modal-ops.js',
'public/js/features/admin/settings/connections-modal-form.js',
'public/js/features/admin/settings/connections-access-modal.js',
      'public/js/features/admin/settings/integrations.js',
'public/js/features/admin/settings/integrations-event-handlers.js',
'public/js/features/admin/settings/integrations-modal-ops.js',
'public/js/features/admin/settings/integrations-access-modal.js',
'public/js/features/admin/settings/policies-acl-helpers.js',
'public/js/features/admin/settings/policies-acl-modal.js',
'public/js/features/admin/settings/policies-event-handlers.js',
'public/js/features/admin/settings/policies-load-family.js',
'public/js/features/admin/settings/policies-rendering.js',
'public/js/features/admin/settings/policies-sticky-header.js',
'public/js/features/admin/settings/policies-state-ops.js',
      'public/js/features/admin/settings/policies.js',
      'public/js/features/admin/users/groups.js',
      'public/js/features/admin/users/overview.js',
    'public/js/features/admin/users/overview-helpers.js',
    'public/js/features/admin/users/overview-render.js',
    'public/js/features/admin/users/overview-controller.js',
      'public/js/features/account/account-connections.js',
      'public/js/features/account/account-integrations.js',
      'public/js/shared/components/connection-modal.js',
      'public/js/shared/markdown-renderer.js',
      'public/js/features/chat/chat-message-actions.js',
      'public/js/features/chat/chat-message-list-html.js',
      'public/js/features/chat/chat-message-retry-actions.js',
      'public/js/features/chat/chat-render-controller.js',
      'public/js/features/chat/chat-data-controller.js',
      'public/js/features/chat/model-selector-controller.js',
      'src/chat/assistant-runner.js',
      'src/llm/connections.js',
      'src/llm/provider-adapters.js',
      'public/js/features/admin/admin.js',
    'public/js/features/admin/admin-controller.js',
      'public/js/features/admin/settings/models.js',
'public/js/features/admin/settings/models-sync-ui.js',
'public/js/features/admin/settings/models-render.js',
'public/js/features/admin/settings/models-event-handlers.js',
'public/js/features/admin/settings/models-access-modal.js',
'public/js/features/admin/settings/models-view.js',
'public/js/features/admin/settings/models-utils.js',
'public/js/features/admin/settings/models-render.js',
'public/js/features/admin/settings/models-event-handlers.js',
'public/js/features/admin/settings/models-access-modal.js',
      // Additional legacy files with existing complexity/line/depth exceedances
      'public/js/bootstrap/app.js',
      'public/js/bootstrap/session-bootstrap.js',
      'public/js/features/account/account-models.js',
      'public/js/features/account/sessions.js',
      'public/js/features/admin/admin-route-state.js',
      'public/js/features/admin/audit-logs.js',
      'public/js/features/admin/settings/connections-helpers.js',
    'public/js/features/admin/settings/connections-helpers-modal-models.js',
      'public/js/features/admin/settings/email-delivery.js',
'public/js/features/admin/settings/models-view.js',
'public/js/features/admin/settings/models-utils.js',
'public/js/features/admin/settings/models-render.js',
'public/js/features/admin/settings/models-event-handlers.js',
'public/js/features/admin/settings/models-access-modal.js',
'public/js/features/admin/settings/integrations-event-handlers.js',
'public/js/features/admin/settings/integrations-modal-ops.js',
'public/js/features/admin/settings/integrations-access-modal.js',
      'public/js/features/admin/settings/general.js',
'public/js/features/admin/settings/policies-acl-helpers.js',
'public/js/features/admin/settings/policies-acl-modal.js',
'public/js/features/admin/settings/policies-event-handlers.js',
'public/js/features/admin/settings/policies-load-family.js',
'public/js/features/admin/settings/policies-rendering.js',
'public/js/features/admin/settings/policies-sticky-header.js',
'public/js/features/admin/settings/policies-state-ops.js',
      'public/js/features/admin/settings/policies.js',
      'public/js/features/admin/settings/registration.js',
      'public/js/features/admin/settings/security.js',
      'public/js/features/admin/settings/security-overview.js',
      'public/js/features/admin/users/roles.js',
      'public/js/features/chat/chat-file-events.js',
      'public/js/features/chat/chat-list-actions.js',
      'public/js/features/chat/chat-message-delete-actions.js',
      'public/js/features/chat/chat-message-dom.js',
      'public/js/features/chat/chat-message-identity.js',
      'public/js/features/chat/chat-message-list-controller.js',
      'public/js/features/chat/chat-message-rendering.js',
      'public/js/features/chat/chat-message-stream-assistant.js',
      'public/js/features/chat/chat-message-stream.js',
      'public/js/features/chat/chat-message-stream-temp-chat.js',
      'public/js/features/chat/chat-message-utils.js',
      'public/js/features/chat/chat-modals.js',
      'public/js/features/chat/chat-shell-controller.js',
      'public/js/features/chat/chat-sidebar-list.js',
      'public/js/features/chat/chat-stream-controller.js',
      'public/js/features/chat/chat-ui-resources.js',
      'public/js/features/chat/model-selector-helpers.js',
      'public/js/shared/api/files.js',
      'public/js/shared/api/models.js',
      'public/js/shared/api/request.js',
      'public/js/shared/components/button.js',
      'public/js/shared/components/chat-placeholder.js',
      'public/js/shared/components/chat-row.js',
      'public/js/shared/components/files-modal-controller.js',
      'public/js/shared/components/form-label-with-helper.js',
      'public/js/shared/components/models-section.js',
      'public/js/shared/components/search-bar.js',
      'public/js/shared/components/search-input.js',
      'public/js/shared/components/search-modal-controller.js',
      'public/js/shared/components/server-modal.js',
      'public/js/shared/components/settings-modal-shell.js',
      'public/js/shared/components/settings-top-nav.js',
      'public/js/shared/components/user-profile-footer-controller.js',
      'public/js/shared/components/viewport-modal-shell.js',
      'public/js/shared/realtime.js',
      'public/js/shared/store.js',
      'public/js/shared/utils/attachment-types.js',
      'public/js/shared/utils/conversation.js',
      'public/js/shared/utils/model-access-presentation.js',
      'public/js/shared/utils/model-filters.js',
      'public/js/shared/utils/model-search.js',
      'public/js/shared/utils/user-resource-overrides.js',
      'public/js/shared/utils/workspace-capabilities.js',
      'src/chat/mcp.js',
      'src/chat/stream-finalize.js',
      'src/chat/stream-lifecycle.js',
      'src/chat/tools.js',
      'src/features/realtime/realtime.js',
      'src/llm.js',
      'src/llm/system-prompt.js',
      'src/mcp/client.js',
      'src/routers/chat-core.js',
      'src/routers/public.js',
      'src/routers/user-profile.js',
      'src/services/uploads.js',
      'src/services/workspace-settings.js',
      'src/utils/validation.js',
      'src/utils/authorize.js',
    ],
    rules: {
      complexity: 'off',
      'no-unused-vars': 'off',
      'max-lines-per-function': 'off',
      'max-depth': 'off',
    },
  },
];
